module.exports = {
  san_francisco: {
    location_id: 2124028216,
    experiences: [
      {
        experience_id: `2124028216a`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: 2124028216,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `2124028216b`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: 2124028216,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `2124028216c`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: 2124028216,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `2124028216d`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: 2124028216,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `2124028216e`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: 2124028216,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `2124028216f`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: 2124028216,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `2124028216g`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: 2124028216,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `2124028216h`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: 2124028216,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `2124028216i`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: 2124028216,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `2124028216j`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: 2124028216,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `2124028216k`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: 2124028216,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `2124028216l`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: 2124028216,
        categories_id: 'somecategoryid'
      }
    ]
  },
  los_angeles: {
    location_id: -1681810253,
    experiences: [
      {
        experience_id: `-1681810253a`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1681810253,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1681810253b`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1681810253,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1681810253c`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1681810253,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1681810253d`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1681810253,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1681810253e`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1681810253,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1681810253f`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1681810253,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1681810253g`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1681810253,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1681810253h`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1681810253,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1681810253i`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1681810253,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1681810253j`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1681810253,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1681810253k`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1681810253,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1681810253l`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1681810253,
        categories_id: 'somecategoryid'
      }
    ]
  },
  new_york: {
    location_id: -365845894,
    experiences: [
      {
        experience_id: `-365845894a`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894b`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894c`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894d`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894e`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894f`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894g`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894h`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894i`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894j`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894k`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894l`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      }
    ]
  },
  philadelphia: {
    location_id: -1560504360,
    experiences: [
      {
        experience_id: `-1560504360a`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1560504360,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1560504360b`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1560504360,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1560504360c`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1560504360,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1560504360d`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1560504360,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1560504360e`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1560504360,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1560504360f`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1560504360,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1560504360g`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1560504360,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1560504360h`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1560504360,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1560504360i`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1560504360,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1560504360j`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1560504360,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1560504360k`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1560504360,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-1560504360l`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -1560504360,
        categories_id: 'somecategoryid'
      }
    ]
  },
  chicago: {
    location_id: -365845894,
    experiences: [
      {
        experience_id: `-365845894a`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894b`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894c`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894d`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894e`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894f`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894g`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894h`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894i`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894j`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894k`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      },
      {
        experience_id: `-365845894l`,
        title: 'sometitle',
        description: 'somedescription',
        photo_url: 'www.url.com',
        is_available: true,
        rating: 5,
        review_count: 100,
        price: 10,
        host_id: 'somehostid',
        location_id: -365845894,
        categories_id: 'somecategoryid'
      }
    ]
  }
};










